service: odds-harvester

provider:
  name: aws
  runtime: python3.9
  region: eu-west-3
  versionFunctions: false
  #environment:
    #API_KEY: ${env:API_KEY}

functions:
  webhook:
    handler: src.main.lambda_handler
    timeout: 30 # seconds
    memorySize: 256 # mb
    description: Retrieve sports betting odds

package:
  individually: true

plugins:
  - serverless-python-requirements
