service: odds-harvester

provider:
  name: aws
  architecture: arm64
  region: eu-west-3
  versionFunctions: false
  ecr:
    images:
      playwrightPython:
        path: ./
        file: Dockerfile
  environment:
    BUCKET_NAME: odds-portal-scrapped-odds
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
          - s3:DeleteObject
        Resource: "arn:aws:s3:::odds-portal-scrapped-odds"

functions:
  scanAndStoreOddsPortalDataV2:
    image:
      name: playwrightPython
    timeout: 300 # seconds
    memorySize: 2048 # mb
    description: Retrieve and store sports betting odds
    events:
      - eventBridge:
        schedule: rate(2 hours)

package:
  individually: true
  patterns:
    - "!node_modules/**"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true
    strip: false  # Set to `true` to remove symbols from compiled files
    noDeploy: ['boto3']  # Exclude packages already available in the AWS environment